### ISSUE TITLE
GoGoAnime

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#121]
### Extension information

GoGoAnime

### Miru version

1.7.2

### Other details

I think this issue is related to the api.

Extension log

```
DioException [bad response]: The request returned an invalid status code of 522.
#0      new JSError (package:flutter_js/quickjs/object.dart:92)
#1      _dartToJs (package:flutter_js/quickjs/wrapper.dart:60)
#2      _JSFunction._invoke.<anonymous closure> (package:flutter_js/quickjs/object.dart:174)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#7      new List.of (dart:core-patch/array_patch.dart:47)
#8      SetBase.toList (dart:collection/set.dart:119)
#9      _JSFunction._invoke (package:flutter_js/quickjs/object.dart:176)
#10     _JSFunction.invoke (package:flutter_js/quickjs/object.dart:155)
#11     _dartToJs.<anonymous closure> (package:flutter_js/quickjs/wrapper.dart:86)
#12     _RootZone.runUnary (dart:async/zone.dart:1661)
#13     _FutureListener.handleError (dart:async/future_impl.dart:174)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#15     Future._propagateToListeners (dart:async/future_impl.dart:873)
#16     Future._completeError (dart:async/future_impl.dart:649)
#17     _RootZone.runBinary (dart:async/zone.dart:1666)
#18     _FutureListener.handleError (dart:async/future_impl.dart:171)
#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#20     Future._propagateToListeners (dart:async/future_impl.dart:873)
#21     Future._completeError (dart:async/future_impl.dart:649)
#22     _SyncCompleter._completeError (dart:async/future_impl.dart:60)
#23     _Completer.completeError (dart:async/future_impl.dart:26)
#24     Future.any.onError (dart:async/future.dart:620)
#25     _RootZone.runBinary (dart:async/zone.dart:1666)
#26     _FutureListener.handleError (dart:async/future_impl.dart:171)
#27     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#28     Future._propagateToListeners (dart:async/future_impl.dart:873)
#29     Future._completeError (dart:async/future_impl.dart:649)
#30     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Yes it's consumet api issue I can change to some other api temperorily if you want me to.

**Comment by bachig26** [comment]
> Yes it's consumet api issue I can change to some other api temperorily if you want me to.

no, it's okay. if it can solved later permanently then it can stay for now. maybe we can keep these both issues open until it's back or fixed for issue logging.

**Comment by OshekharO** [comment]
> > Yes it's consumet api issue I can change to some other api temperorily if you want me to.
> 
> no, it's okay. if it can solved later permanently then it can stay for now. maybe we can keep these both issues open until it's back or fixed for issue logging.

Well let's switch to temp because official api now only for demo purpose 😕
